version: 2

updates:
  - package-ecosystem: github-actions
    directory: /.github/workflows
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(deps)"
    labels:
      - dependencies
      - github-actions
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /packages/typescript
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(deps)"
    labels:
      - dependencies
      - typescript
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: gomod
    directory: /packages/golang
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(deps)"
    labels:
      - dependencies
      - go
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: cargo
    directory: /packages/rust
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(deps)"
    labels:
      - dependencies
      - rust
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: pip
    directory: /packages/python
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(deps)"
    labels:
      - dependencies
      - python
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
